name: Publish npm + GitHub Packages

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js for npmjs
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test || echo "No tests found"

    - name: Publish to npmjs (unscoped)
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --access public

    - name: Prepare package.json for GitHub Packages
      run: |
        # Backup original package.json
        cp package.json package.json.bak

        # Replace name with scoped package name
        jq '.name = "@gorav22/promptlang"' package.json > package.scoped.json

        # Replace package.json with scoped one
        mv package.scoped.json package.json

    - name: Setup Node.js for GitHub Packages
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://npm.pkg.github.com/

    - name: Publish to GitHub Packages (scoped)
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: npm publish

    - name: Restore original package.json
      run: mv package.json.bak package.json
